# Generated by Django 3.2 on 2023-10-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20231029_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioRecording',
        ),
    ]
