# Generated by Django 3.2 on 2023-10-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_recordedvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='recordings/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RecordedVoice',
        ),
    ]
