# Generated by Django 4.2.7 on 2023-11-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20231029_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioRecording',
        ),
    ]
